# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0667455431f894237ffba6fc0e98242dc2720291dfa38adc97c1c4f6327d2b94f8f2bd0fb1450acf3f557b5e03829e0564442f09746c5da7683f8f43565c7ef

test:
  secret_key_base: e93d51abeeb922826edcf9532c112940a411cbcbed9fdb465580afa9a4e173ac352542d251b6b18cc409d9319df367bc2e6b5ebb6d12dddf75fd72ffc4707372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
